name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Briefcase
        run: |
          pip install briefcase

      - name: Create APK
        run: |
          briefcase build android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: meu_apk
          path: target/android/app/build/outputs/apk/debug/*.apk